### ISSUE TITLE
TypeError: Path must be a string. Received undefined (in node 6.x)

### ISSUE THREAD

**Issue by gavinr** [tomwayson/esri-rollup-example#32]
I'm getting an error `TypeError: Path must be a string. Received undefined` when running the clean repo.

Replication steps:
1. Clone repo
2. `npm install`
3. `npm start`
4. gives me this output:

<details>
 <summary>

Error output</summary>

```
λ npm start

> esri-rollup-example@0.1.8 start f:\gh\esri-rollup-example
> gulp serve

(node:8904) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[22:14:25] Using gulpfile f:\gh\esri-rollup-example\gulpfile.js
[22:14:25] Starting 'clean'...
[22:14:25] Finished 'clean' after 5.37 ms
[22:14:25] Starting 'serve'...
[22:14:25] Starting 'lint'...
[22:14:25] Starting 'fonts'...
[22:14:25] Starting 'scripts:vendor'...
[22:14:25] Starting 'scripts:nls'...
[22:14:25] Starting 'scripts:app'...
[22:14:25] Starting 'styles'...
[22:14:26] Starting 'html'...
[22:14:26] Finished 'serve' after 468 ms
Treating 'dojo/_base/declare' as external dependency
Treating 'dijit/_WidgetBase' as external dependency
Treating 'dijit/_TemplatedMixin' as external dependency
Treating 'esri/Map' as external dependency
Treating 'esri/views/MapView' as external dependency
Treating 'esri/layers/FeatureLayer' as external dependency
Treating 'esri/widgets/BasemapToggle' as external dependency
Treating 'esri/widgets/BasemapToggle/BasemapToggleViewModel' as external dependency
Treating 'dojo/i18n!./nls/strings' as external dependency
[22:14:26] 'scripts:app' errored after 703 ms
[22:14:26] Error
    at new JS_Parse_Error (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at as_symbol (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2740:27)
    at vardefs (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2508:25)
    at var_ (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2522:27)
    at eval (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2265:30)
    at eval (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (f:\gh\esri-rollup-example\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2401:25)
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:889:5)
    at processText (f:\gh\esri-rollup-example\node_modules\standard-engine\node_modules\eslint\lib\cli-engine.js:191:30)
    at CLIEngine.executeOnText (f:\gh\esri-rollup-example\node_modules\standard-engine\node_modules\eslint\lib\cli-engine.js:678:26)
    at Linter.lintText (f:\gh\esri-rollup-example\node_modules\standard-engine\index.js:60:54)
    at DestroyableTransform.processFile [as _transform] (f:\gh\esri-rollup-example\node_modules\gulp-semistandard\index.js:22:18)
    at DestroyableTransform.Transform._read (f:\gh\esri-rollup-example\node_modules\gulp-semistandard\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (f:\gh\esri-rollup-example\node_modules\gulp-semistandard\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (f:\gh\esri-rollup-example\node_modules\gulp-semistandard\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (f:\gh\esri-rollup-example\node_modules\gulp-semistandard\node_modules\readable-stream\lib\_stream_writable.js:227:5)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\g\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! esri-rollup-example@0.1.8 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esri-rollup-example@0.1.8 start script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the esri-rollup-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs esri-rollup-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls esri-rollup-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     f:\gh\esri-rollup-example\npm-debug.log
f:\gh\esri-rollup-example
```

</details>

Environment:

```
λ node -v
v6.2.2
λ npm -v
3.7.5

Windows 7
```

**Comment by tomwayson** [comment]
This is looking like a [node 6 issue affecting a lot of projects](https://www.google.com/#q=path%20must%20be%20a%20string.%20received%20undefined%20node%206). I saw same error on my machine, on node 6.3.0. However, after reverting back to node 5 and running `rm -rf node_modules && npm i`, I get a _different_ error:

```
➜  esri-rollup-example git:(master) ✗ nvm ls
         v4.4.2
->      v5.11.0
         v6.3.0
default -> 6.3.0 (-> v6.3.0)
node -> stable (-> v6.3.0) (default)
stable -> 6.3 (-> v6.3.0) (default)
iojs -> N/A (default)
➜  esri-rollup-example git:(master) ✗ npm run start

> esri-rollup-example@0.1.8 start /Users/tom6947/code/esri-rollup-example
> gulp serve

[07:17:56] Using gulpfile ~/code/esri-rollup-example/gulpfile.js
[07:17:56] Starting 'clean'...
[07:17:56] Finished 'clean' after 15 ms
[07:17:56] Starting 'serve'...
[07:17:56] Starting 'lint'...
[07:17:56] Starting 'fonts'...
[07:17:56] Starting 'scripts:vendor'...
[07:17:56] Starting 'scripts:nls'...
[07:17:56] Starting 'scripts:app'...
[07:17:56] Starting 'styles'...
[07:17:56] Starting 'html'...
[07:17:56] Finished 'serve' after 287 ms
Treating 'dojo/_base/declare' as external dependency
Treating 'dijit/_WidgetBase' as external dependency
Treating 'dijit/_TemplatedMixin' as external dependency
Treating 'esri/Map' as external dependency
Treating 'esri/views/MapView' as external dependency
Treating 'esri/layers/FeatureLayer' as external dependency
Treating 'esri/widgets/BasemapToggle' as external dependency
Treating 'esri/widgets/BasemapToggle/BasemapToggleViewModel' as external dependency
Treating 'dojo/i18n!./nls/strings' as external dependency
[07:17:57] 'scripts:app' errored after 450 ms
[07:17:57] Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at as_symbol (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2740:27)
    at vardefs (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2508:25)
    at var_ (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2522:27)
    at eval (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2265:30)
    at eval (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (/Users/tom6947/code/esri-rollup-example/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2401:25)
[07:17:57] Finished 'html' after 825 ms
[07:17:57] Finished 'scripts:nls' after 839 ms
[07:17:59] Finished 'lint' after 2.75 s
[07:17:59] Finished 'styles' after 2.48 s
[07:17:59] Finished 'scripts:vendor' after 2.52 s
[07:17:59] Finished 'fonts' after 2.53 s

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/tom6947/.nvm/versions/node/v5.11.0/bin/node" "/Users/tom6947/.nvm/versions/node/v5.11.0/bin/npm" "run" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! esri-rollup-example@0.1.8 start: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esri-rollup-example@0.1.8 start script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the esri-rollup-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs esri-rollup-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls esri-rollup-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tom6947/code/esri-rollup-example/npm-debug.log
```

So something is up.

**Comment by gavinr** [comment]
I just tested on Node 4.x and got effectively the same error that you just posted. So I would agree that my original issue is related to using Node 6.x.

**Comment by tomwayson** [comment]
I can confirm that #33 did not solve this for node 6. 😞 

For now, best to not use this w/ node 6.

**Comment by tomwayson** [comment]
Closing this as I'm deprecating this repo in favor of using [esri-loader](https://github.com/Esri/esri-loader/).
