### ISSUE TITLE
Error transforming App.js with 'babel' plugin

### ISSUE THREAD

**Issue by gavinr** [tomwayson/esri-rollup-example#35]
If I do a clean clone and `npm install` today, I get the following error:

```
> gulp serve

[20:05:19] Using gulpfile C:\gh\esri-rollup-example\gulpfile.js
[20:05:19] Starting 'clean'...
[20:05:19] Finished 'clean' after 16 ms
[20:05:19] Starting 'serve'...
[20:05:19] Starting 'lint'...
[20:05:20] Starting 'fonts'...
[20:05:20] Starting 'scripts:vendor'...
[20:05:20] Starting 'scripts:nls'...
[20:05:20] Starting 'scripts:app'...
[20:05:20] Starting 'styles'...
[20:05:20] Starting 'html'...
[20:05:20] Finished 'serve' after 416 ms
[20:05:20] 'scripts:app' errored after 182 ms
[20:05:20] Error: Error transforming C:\gh\esri-rollup-example\src\app\App.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (C:\gh\esri-rollup-example\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (C:\gh\esri-rollup-example\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:104:18)
    at C:\gh\esri-rollup-example\node_modules\rollup\dist\rollup.js:6981:35
[20:05:20] Finished 'html' after 626 ms
[20:05:20] Finished 'scripts:nls' after 647 ms
[20:05:22] Finished 'styles' after 2.18 s
[20:05:22] Finished 'lint' after 2.6 s
[20:05:22] Finished 'scripts:vendor' after 2.27 s
[20:05:22] Finished 'fonts' after 2.27 s
```

.. which is weird because the version that I did `npm install` about a month ago (no `package.json` changes since then) works fine. So I gotta think it's a minor NPM package dependancy issue.

**Comment by tomwayson** [comment]
I just pulled master, and ran:

```
rm -rf node_modules && npm i
npm start
```

And the app builds and runs fine for me. Here's what I have installed (at the top level)

```
esri-rollup-example git:(master) npm ls --depth=0
esri-rollup-example@0.1.9 /Users/tom6947/code/esri-rollup-example
├── babel-preset-es2015-rollup@1.2.0
├── browser-sync@2.15.0
├── calcite-bootstrap@0.3.3
├── del@2.2.2
├── gulp@3.9.1
├── gulp-concat@2.6.0
├── gulp-debug@2.1.2
├── gulp-gh-pages@0.5.4
├── gulp-if@2.0.1
├── gulp-load-plugins@1.2.4
├── gulp-rename@1.2.2
├── gulp-sass@2.3.2
├── gulp-semistandard@0.2.2
├── gulp-size@2.1.0
├── gulp-sourcemaps@1.6.0
├── gulp-uglify@1.5.4
├── jquery@2.2.4
├── lodash-es@4.15.0
├── rollup@0.34.13
├── rollup-plugin-babel@2.6.1
├── rollup-plugin-string@1.0.1
├── rollup-plugin-uglify@1.0.1
└── semistandard@7.0.5
```

I'm on node 5.11.0 and npm 3.8.6 on OSX.

**Comment by gavinr** [comment]
After looking at the differences between the `node_modules` folder I had a month ago, and what is showing up today, seems like i'm getting a different version of `babel-preset-es2015` now (6.14.0) vs a month ago (6.9.0), even though same version of `babel-preset-es2015-rollup`. When I manually copy babel-preset-es2015@6.9.0, it starts working. So I guess it's some issue with that and my environment:
- Windows 7
- npm -v
  - 3.7.5
- node -v
  - v4.4.7

![image](https://cloud.githubusercontent.com/assets/209355/18298511/beb19a24-747e-11e6-8dac-a32c9e8d38ff.png)

I'll close this since it's clearly not an issue with this repo. Thanks for verifying.

**Comment by gavinr** [comment]
for posterity sake, looks like similar or same to this issue:
https://github.com/rollup/rollup/issues/946
